{version: 2.0.5, docker_context: ., build_docker_file: docker/Dockerfile.building,
  build_method: nope_build, update_method: python_update, python_version_file: tassandra/version.py,
  deploy_method: nope_deploy}
