language: python
matrix:
  include:
    - os: linux
      dist: trusty
      python: "3.9"
install:
  - pip3 install codecov
  - python3 setup.py install
script:
  - python3 setup.py test
sudo: false
after_success:
  - rm .coverage -f
  - coverage run setup.py test
  - coverage report -m
  - bash <(curl -s https://codecov.io/bash)
