FROM registry.pyn.ru/python3.9-ubuntu20-production:2022.10.24

RUN mkdir -p /home/build
WORKDIR /home/build

COPY tassandra tassandra
COPY tests tests
COPY pyproject.toml pyproject.toml
COPY poetry.lock poetry.lock
COPY README.md README.md

RUN apt-get update && apt-get install -y openjdk-8-jre-headless

# Тесты не проходят на hh-release
# RUN python3.9 setup.py test
