FROM registry.pyn.ru/python3.7-ubuntu18-production:2020.12.28

RUN mkdir -p /home/build
WORKDIR /home/build

COPY tassandra tassandra
COPY tests tests
COPY setup.py setup.py
COPY README.md README.md

RUN apt-get update && apt-get install -y openjdk-8-jre-headless

# Тесты не проходят на hh-release
# RUN python3.7 setup.py test
